---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp terms-and-conditions.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH